services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    network_mode: host
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: host
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
